# Generated by Django 3.2.6 on 2023-08-19 20:59

import app.models.usermodel
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date Time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date Time on which the object was last modified', verbose_name='modified at')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exist.'}, max_length=254, unique=True, verbose_name='emailAddres')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this', verbose_name='staff status')),
                ('is_activate', models.BooleanField(default=False, help_text='Set to true when the user have active its email address.', verbose_name='active')),
                ('is_active', models.BooleanField(default=False, help_text='Set to true when the user have active its email address.', verbose_name='active')),
                ('is_verified', models.BooleanField(default=False, help_text='Set to true when the user have verified its email address.', verbose_name='verified')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
            managers=[
                ('objects', app.models.usermodel.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InventPackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date Time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date Time on which the object was last modified', verbose_name='modified at')),
                ('dateNum', models.IntegerField(blank=True, null=True, verbose_name='N° Fechas')),
                ('descriptionPack', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('priceUnit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precio')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuitTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date Time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date Time on which the object was last modified', verbose_name='modified at')),
                ('namesuit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre')),
                ('descriptionsuit', models.CharField(blank=True, max_length=15, null=True, verbose_name='Descripción')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReserveTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date Time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date Time on which the object was last modified', verbose_name='modified at')),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('remainingChanges', models.PositiveIntegerField(default=1)),
                ('suitId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.suittable')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerPurchTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date Time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date Time on which the object was last modified', verbose_name='modified at')),
                ('state', models.BooleanField(blank=True, null=True, verbose_name='Pagado')),
                ('priceTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precio Total')),
                ('itemId', models.ManyToManyField(blank=True, to='app.InventPackTable')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
